export const UI_TEXT = {
  vi: {
    newProject: "Tạo dự án mới",
    createProject: "+ Tạo dự án",
    noProjects: "Không có dự án nào.",
    workspaceDescription: "Không gian làm việc sinh viên với phản hồi từ giảng viên",
    history: "Lịch sử",
    revise: "Chỉnh sửa",
    signOut: "Đăng xuất",
    paperDrafts: "Phần bài viết",
    sources: "Tài nguyên đa phương tiện",
    sampleDocument: "Sample Document — Select or Create a Paper",
    tabInfo: "Thông tin",
    tabClaims: "Luận điểm",
    tabFeedback: "Nhận xét",
    tabGraph: "Đồ thị",
    aiReview: "AI Review",
    feedbacks: "phản hồi",
  },
  en: {
    newProject: "Create New Project",
    createProject: "+ Create Project",
    noProjects: "No projects found.",
    workspaceDescription: "Student workspace with returned Instructor feedback",
    history: "History",
    revise: "Revise",
    signOut: "Sign Out",
    paperDrafts: "Paper Sections",
    sources: "Media Assets",
    sampleDocument: "Sample Document — Select or Create a Paper",
    tabInfo: "Info",
    tabClaims: "Claims",
    tabFeedback: "Feedback",
    tabGraph: "Graph",
    aiReview: "AI Review",
    feedbacks: "feedbacks",
  }
};
